### ISSUE TITLE
Application has no icon in overview when running on pmOS / Phosh

### ISSUE THREAD

**Issue by heldderarbeit** [blissd/fotema#211] opened 2024-09-26 14:13 UTC
Hello, I'm trying Fotema 1.14.2 on a mobile linux phone (postmarketOS Edge with Phosh). When running in the overview, the application has no icon set (just a generic question mark in a circle).

![20240926_15h46m52s_grim Edited Edited](https://github.com/user-attachments/assets/3cae6612-0bb0-4a9c-b53f-51f01db64a6d)

Other applications usually show the icon while doing this. Below are some examples attached.

![20240926_15h49m17s_grim Edited](https://github.com/user-attachments/assets/ef43170f-572c-43c3-b301-c8e4d9a191bb)
![20240926_15h51m03s_grim Edited](https://github.com/user-attachments/assets/5870a3ae-b578-4dc0-bb88-b6d83878892d)
![20240926_16h05m58s_grim Edited](https://github.com/user-attachments/assets/4a0672ed-f2c3-49c6-90fd-1ea38909b540)

**Comment by NelvinBHV** [comment] 2024-09-26 14:54
I think your OS uses Wayland for graphical display. Under Wayland, you need to add StartupWMClass=fotema at the very bottom of the app.fotema.Fotema.desktop file. I believe this should resolve the issue.

**Comment by heldderarbeit** [comment] 2024-09-26 16:18
I copied `app.fotema.Fotema.desktop` from `/var/lib/flatpak/app/app.fotema.Fotema/aarch64/stable/6dd2b2ffb0a7129637daff8efe26118a9775327bd12601bdb5be8b4af9130ee1/export/share/applications` to my local `~/.local/share/applications` and added the line `StartupWMClass=fotema`, but couldn't get the icon to show up. Even after restarting the phone and adding and removing `Hidden=true`.

**Comment by blissd** [comment] 2024-09-26 18:48
Hi @heldderarbeit. Thank you for your detailed bug report. I'm happy to update the desktop file and cut a new release if you think it will help. Have you tried `StartupWMClass=app.fotema.Fotema`, too?

**Comment by blissd** [comment] 2024-09-26 18:56
I've looked at the `.desktop` files of some of the apps you provided screenshots of, and I didn't spot the `StartupWMClass` lines. Here is the file for[ Door Knocker](https://codeberg.org/tytan652/door-knocker/src/branch/main/data/xyz.tytanium.DoorKnocker.desktop.in.in).

**Comment by heldderarbeit** [comment] 2024-09-26 20:31
Sadly `StartupWMClass=app.fotema.Fotema` doesn't work either.

**Comment by NelvinBHV** [comment] 2024-09-27 02:01
I just checked the WMClass for the Flatpak using Looking Glass. StartupWMClass=fotema is correct. However, I initially had an issue with the icon. After changing the icon path to an absolute path, it worked. I created these patches for my ebuild:
https://github.com/NelvinBHV/PortagePirats/tree/main/media-gfx/fotema/files

**Comment by NelvinBHV** [comment] 2024-09-27 03:04
> I've looked at the `.desktop` files of some of the apps you provided screenshots of, and I didn't spot the `StartupWMClass` lines. Here is the file for[ Door Knocker](https://codeberg.org/tytan652/door-knocker/src/branch/main/data/xyz.tytanium.DoorKnocker.desktop.in.in).

It is a issue in combination with gnome3 and wayland

**Comment by NelvinBHV** [comment] 2024-09-27 03:33
In a .desktop file, which is used on Linux to launch applications on the desktop, the StartupWMClass field is an optional entry that specifies the Window Manager class of an application. This value is used by the window manager (like GNOME, KDE, etc.) to correctly associate the windows of an application, particularly when it comes to displaying the correct icon or grouping the window under the correct running application.

**Purpose of** **_StartupWMClass_:**

- Icon Association: It helps ensure that the correct icon is used for the application, especially if an application can open multiple windows with different WM classes.

- Window Grouping: In some window managers, windows of an application can be grouped together, and StartupWMClass ensures that this grouping is done correctly.

**Example:**
Suppose you have a .desktop file for an application called "MyApp." The application might open windows that appear under the WM class as "myapp-main" or "myapp-settings." By adding StartupWMClass=myapp-main in the .desktop file, you can ensure that the window manager correctly recognizes and associates the main window of the application.

[Desktop Entry]
Name=MyApp
Exec=/usr/bin/myapp
Icon=myapp
StartupWMClass=myapp-main
Type=Application

**Comment by heldderarbeit** [comment] 2024-09-27 11:32
> After changing the icon path to an absolute path, it worked. I created these patches for my ebuild: https://github.com/NelvinBHV/PortagePirats/tree/main/media-gfx/fotema/files

I changed my local `app.fotema.Fotema.desktop` file as you did in your patch (`StartupWMClass=fotema` and `Icon=/home/user/.local/share/icons/hicolor/scalable/fotema/app.fotema.Fotema.svg`, image beforehand copied from the Flatpak folder). Unfortunately that doesn't fix the original issue 🙁

**Comment by NelvinBHV** [comment] 2024-09-27 14:11
Ich gehe mal aufgrund Deine Benutzernamens davon aus, dass Du aus Deutschland kommst. 
Hast Du mal probiert die Datei unter ~/.local/share/flatpak/exports/share/applications direkt anzupassen?

I changed my local `app.fotema.Fotema.desktop` file as you did in your patch (`StartupWMClass=fotema` and `Icon=/home/user/.local/share/icons/hicolor/scalable/fotema/app.fotema.Fotema.svg`, image beforehand copied from the Flatpak folder). Unfortunately that doesn't fix the original issue 🙁

> > After changing the icon path to an absolute path, it worked. I created these patches for my ebuild: https://github.com/NelvinBHV/PortagePirats/tree/main/media-gfx/fotema/files
> 
> I changed my local `app.fotema.Fotema.desktop` file as you did in your patch (`StartupWMClass=fotema` and `Icon=/home/user/.local/share/icons/hicolor/scalable/fotema/app.fotema.Fotema.svg`, image beforehand copied from the Flatpak folder). Unfortunately that doesn't fix the original issue 🙁

**Comment by heldderarbeit** [comment] 2024-09-27 17:37
> After changing the icon path to an absolute path, it worked. 

I'm wondering about this part - Can you specify what exactly you mean by saying that it "worked"? Because as far as I can see, this issue is Phosh specific. It can't be reproduced on Gnome Shell, for example. So am starting to think that maybe we are talking about two different issues. Can you confirm that it works on **Phosh** for you? 

> ~/.local/share/flatpak/exports/share/applications

That folder is empty for me (except from an mimeinfo.cache file).

The app seems to be installed in /var/lib/flatpak/app/app.fotema.Fotema/aarch64/stable. And directly changing the desktop file in there - Maybe I did something wrong, but I didn't make any progress.

**Comment by heldderarbeit** [comment] 2024-09-27 22:24
@blissd 

I have news from [Phosh developer Guido](https://gitlab.gnome.org/World/Phosh/phosh/-/issues/1121#note_2233663):

> The fotema's toplevels app-id doesn't match the desktop file name, hence:
> 
> `Sep 27 22:34:13 qwark phosh[23291]: Could not find application for app-id 'fotema'`
> it should be app.fotema.Fotema. We handle some oddities in phosh_get_desktop_app_info_for_app_id. It would be best to fix fotema though. https://honk.sigxcpu.org/con/GTK__and_the_application_id.html could help.

**Comment by blissd** [comment] 2024-09-28 10:15
Fix is in v1.14.3 which should be available on Flathub later today. Please let me know if it actually fixes the problem or if it still persists.

**Comment by heldderarbeit** [comment] 2024-09-28 12:02
Sorry to say that this issue still persists. Even after updating to the latest version v1.14.3, deleting all app data and doing a clean install 😭

**Comment by blissd** [comment] 2024-09-28 12:05
Sorry 😞 

From the phosh developer comments I thought the fix was to add StartupWMClass=app.fotema.Fotema. Perhaps I misunderstood what was meant?

**Comment by NelvinBHV** [comment] 2024-09-28 12:57
Unfortunately, I am not a Phosh developer either; I just have the same problem when I set the StartupWMClass to something other than 'fotema'. In my desktop file, it says StartupWMClass=fotema. That way, I also have an icon when I use fotema.
But I think this might be where the problem lies. The app ID is app.fotema.Fotema, but when I check with Looking Glass under GNOME to see which WMClass is being used, it says 'fotema'.

**Comment by blissd** [comment] 2024-09-28 13:11
@NelvinBHV Where do you see the application id as `fotema`? I see it as blank:

![image](https://github.com/user-attachments/assets/b0c54d68-0200-4383-9f5f-89685a4bd75d)

**Comment by NelvinBHV** [comment] 2024-09-28 13:31
I only see the wmclass if i use lg (looking glass) under gnome:
![Bildschirmfoto vom 2024-09-28 15-29-28](https://github.com/user-attachments/assets/99be4cde-53dc-4e6b-8826-286f6bebd5cb)

**Comment by NelvinBHV** [comment] 2024-09-28 14:44
I just check the pull request #216. For me it works

**Comment by blissd** [comment] 2024-09-28 19:17
Fotema v.1.14.4 has been released and should show up on Flathub soon. The release contains agx's fix from PR #216. Please let me know if the problem is fixed.

**Comment by heldderarbeit** [comment] 2024-09-29 02:54
Thanks for working on this, everyone. It really works as expected now.

![20240929_04h14m56s_grim Edited](https://github.com/user-attachments/assets/2c760215-990a-4fc3-a2a0-9cf95eea1db9)

**Closed** 2024-09-29 02:55 UTC
