### ISSUE TITLE
Feature Request: show file in folder

### ISSUE THREAD

**Issue by 0chroma** [blissd/fotema#115] opened 2024-08-01 08:02 UTC
It would be nice if I could browse to the underlying file in my file browser. Maybe as a link in the info sidebar?

**Comment by blissd** [comment] 2024-08-01 08:04
Fotema already supports this feature. For the photo or video you are viewing open the info bar and click the folder icon by the file name. Your file manager should open with the file selected.

**Comment by blissd** [comment] 2024-08-01 08:16
A minor correction... the folder icon is next to the folder name, not the file name.
![image](https://github.com/user-attachments/assets/5aa3c3ef-0881-4818-ae6c-58754a8cc1a1)

**Comment by 0chroma** [comment] 2024-08-01 08:21
ah okay, how recently was that added? I don't seem to see it in the current flatpak version

**Comment by blissd** [comment] 2024-08-01 08:32
> ah okay, how recently was that added? I don't seem to see it in the current flatpak version

This feature has been present since version [1.1.0](https://github.com/blissd/fotema/releases/tag/v1.1.0) which was released in May.

If the folder open icon is not present, then please let me know what version of Fotema you are running and if there is anything curious about your setup.

**Comment by 0chroma** [comment] 2024-08-01 08:58
I'm using version 1.9.6, here's a screenshot from the app:
![Screenshot from 2024-08-01 01-57-32](https://github.com/user-attachments/assets/ef2c2a8c-56d5-4f89-8861-64c8e7be40dd)

Nothing particularly novel about my setup, mainly just using the flatpak version.

**Comment by blissd** [comment] 2024-08-01 09:04
Hmm.... perhaps I closed this issue too hastily, that looks like a bug! I see that I can reproduce the folder icon being missing if I move a photo to the root of my pictures directory.

**Comment by 0chroma** [comment] 2024-08-01 09:05
ahh, yeah that's how I have my photos folder structured, they're all in one root folder. So that would make sense actually!

**Closed** 2024-08-06 19:06 UTC

**Comment by 0chroma** [comment] 2024-08-08 13:57
just tested, it works! tyyy
